app:
  rabbitmq:
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant

server:
  port: 0
  # Using a random port to avoid conflicts with other instances of the service.

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.3:8761/eureka

spring:
  zipkin:
    base-url: http://172.17.0.4:9411
  main:
    allow-circular-references: true
  rabbitmq:
    host: 172.17.0.5