spring:
  datasource:
    # Uso del server MySQL
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://172.17.0.11:9091/PizzaService
   username: root
   password: root
  jpa:
    # Connettore del database.
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  zipkin:
    base-url: http://172.17.0.4:9411
  main:
    allow-circular-references: true
  rabbitmq:
    host: 172.17.0.5

server:
  port: 0
  # Using a random port to avoid conflicts with other instances of the service.
  servlet:
    context-path: /api

app:
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.3:8761/eureka

# Swagger UI
# http://localhost:9090/api/swagger-ui/index.html
# 192.168.1.160:9090/api/swagger-ui/index.html

# H2-Console
# http://localhost:9090/api/h2-console
# 192.168.1.160:9090/api/h2-console
# Inserire come db:
# jdbc:h2:file:~/data/PizzaServiceDB
# Username e Password sono entrambe sa.