spring:
  datasource:
    # Uso del server MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.10:9090/RestaurantService
    username: root
    password: root
  jpa:
    # Connettore del database.
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  zipkin:
    base-url: http://172.17.0.4:9411
  main:
    allow-circular-references: true
  rabbitmq:
    host: 172.17.0.5

server:
  port: 0
  # Using a random port to avoid conflicts with other instances of the service.
  servlet:
    context-path: /api

app:
  pizza-service-url: http://172.17.0.6:8080/api/pizzas/restaurant
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    notify-pizzas-added-routingkey: q.notify-pizzas-added-to-restaurant

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.3:8761/eureka

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      addPizzasToRestaurantCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60
  retry:
    retry-aspect-order: 2
    instances:
      retryAddPizzasToRestaurant:
        max-attempts: 3
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException

# Swagger UI
# http://localhost:9091/api/swagger-ui/index.html
# 192.168.1.160:9091/api/swagger-ui/index.html

# H2-Console
# http://localhost:9091/api/h2-console
# 192.168.1.160:9091/api/h2-console
# Inserire come db:
# jdbc:h2:file:~/data/RestaurantServiceDB
# Username e Password sono entrambe sa.